spring:
  h2:
    # 자동으로 H2 DB를 in-memory DB로 부팅시켜 준다.
    console:
      enabled: true
  jpa:
    # Spring Boot 2.5 버전부터는 data.sql이 Hibernate 가 초기화되기 전에 실행되어
    # Hibernate 초기화를 통해 생성된 스키마에 데이터를 입력하기 위해 data.sql을 실행하려면
    # 1) application.yml 에 spring.jpa.defer-datasource-initialization = true 추가
    # 2) schema.sql 을 추가 (권장하지 않음)
    # 해야 한다.
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

