spring:
  h2:
    # 자동으로 H2 DB를 in-memory DB로 부팅시켜 준다.
    console:
      enabled: true
  jpa:
    # spring 2.5.x 부터 적용. hibernate 초기화를 data.sql 보다 먼저 실행되도록 해주는 설정.
    defer-datasource-initialization: true
    # sql 쿼리 넣는 것을 보여준다.
    show-sql: true
    properties:
      hibernate:
        # sql 쿼리가 정렬되게 나오도록 한다.
        format_sql: true
  datasource:
    # jdbc api를 사용할 것이고, mysql db driver를 쓸 것이고, 주소는 localhost.
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password: abcd

